import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faChevronLeft,
    faChevronRight,
    faSignInAlt,
    faSignOutAlt,
    faUser,
    faMoneyCheckAlt,
    faExclamation,
    faMedal,
    faCoins,
    faGift,
    faReply,
    faTimes,
    faTasks,
    faFileUpload,
    faUsersCog,
    faCog,
    faGavel,
    faUnlockAlt,
    faLock,
    faInfinity,
    faBox,
    faSyncAlt,
    faStar,
    faWallet,
    faPeopleArrows,
    faQuestion,
    faEnvelope,
    faEnvelopeOpen,
    faUndoAlt,
    faAngleUp,
    faExclamationTriangle,
    faSnowflake,
    faDollarSign,
} from "@fortawesome/free-solid-svg-icons";
import {
    faBuffer,
    faFacebookF,
    faTwitter,
    faRedditAlien,
} from "@fortawesome/free-brands-svg-icons";
import {
    faHandshake,
    faCopy,
    faTrashAlt,
    faEye,
} from "@fortawesome/free-regular-svg-icons";

export default {
  icons: library.add(
    // Solid
    faChevronRight,
    faChevronLeft,
    faSignInAlt,
    faSignOutAlt,
    faUser,
    faMoneyCheckAlt,
    faExclamation,
    faMedal,
    faCoins,
    faGift,
    faReply,
    faTimes,
    faTasks,
    faFileUpload,
    faUsersCog,
    faCog,
    faGavel,
    faUnlockAlt,
    faLock,
    faInfinity,
    faBox,
    faSyncAlt,
    faStar,
    faWallet,
    faPeopleArrows,
    faQuestion,
    faEnvelope,
    faEnvelopeOpen,
    faUndoAlt,
    faAngleUp,
    faExclamationTriangle,
    faSnowflake,
    faDollarSign,

    // Brands
    faBuffer,
    faFacebookF,
    faTwitter,
    faRedditAlien,

    // Regular
    faHandshake,
    faCopy,
    faTrashAlt,
    faEye,
  ),
};
